### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by merlinarer** [kinredon/umt#1]
Hello~ I have several questions about the dataset in your paper.
For PASCAL VOC→Clipart1k adaptation, the source baseline is trained on original pascal voc 2007+2012 or the one translated by cyclegan?
For Cityscapes→Foggy Cityscapes adaptation, since there are 3 level (0.01, 0.02, 0.005) in Foggy Cityscapes, which one is used in this paper?

**Comment by kinredon** [comment]
The source baseline is trained on original pascal voc07+12 for PASCAL VOC→Clipart1k. For  Cityscapes→Foggy Cityscapes adaptation, we choose 0.02 which is the foggiest.

**Comment by merlinarer** [comment]
> The source baseline is trained on original pascal voc07+12 for PASCAL VOC→Clipart1k. For Cityscapes→Foggy Cityscapes adaptation, we choose 0.02 which is the foggiest.

Thank you for your reply, since I got a very low mAP=16 in source baseline for PASCAL VOC→Clipart1k, I trained on original pascal voc07+12 , and test on original  Clipart1k test set, is there something special for PASCAL VOC→Clipart1k camparing other experiments?

**Comment by kinredon** [comment]
In fact, there is no special for PASCAL VOC→Clipart1k, you may take a look at other experiments? 

btw, here do your mAP indicates AP 50 or coco style mAP?

**Comment by merlinarer** [comment]
> In fact, there is no special for PASCAL VOC→Clipart1k, you may take a look at other experiments?
> 
> btw, here do your mAP indicates AP 50 or coco style mAP?

yeah, AP50, I will try on other dataset.
