### ISSUE TITLE
Can torch1.8 run this project?

### ISSUE THREAD

**Issue by yuninn** [kinredon/umt#10]
Thank you for providing such an excellent project, I have a high CUDA version, can torch 1.8 run this project?

**Comment by kinredon** [comment]
@yuninn It is a pity that this repo cannot run in torch 1.8. However, you can follow the torch1.0 branch of [faster-rcnn.pytorch](https://github.com/jwyang/faster-rcnn.pytorch/tree/pytorch-1.0) to remold this repo. The main difference between them is the part of the NMS extension.
