### ISSUE TITLE
作者您好，请教一个训练流程的问题。

### ISSUE THREAD

**Issue by Donghuan777** [kinredon/umt#14]
作者您好，感谢您的研究，请问训练流程是怎样的？论文中提到使用Source数据和Target-Like数据对Student进行supervison训练，是先用Source训练然后再用Target-Like训练，这两个supervison训练完开始Teacher和Student的共同训练吗？

**Comment by kinredon** [comment]
你可以看看 train.py 里面的训练流程，
https://github.com/kinredon/umt/blob/621ab9d3fe2ea7c223f300f9184fedc7db6da780/umt_train.py#L270
是把所有的损失函数加在一起后backward再更新的模型
