### ISSUE TITLE
Setup issue

### ISSUE THREAD

**Issue by ae208gpu** [kinredon/umt#18]
Hi I currently have a 3090Ti looking to replicate your work for conducting studies.

My Python anaconda env version is 2.7 and torch is 1.0.0 
I have been able to build the faster-rcnn model but I am not able to run your code

raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")

**Comment by kinredon** [comment]
@ae208gpu It is recommended to use python3, PyTorch 0.4.0 to run this project. 

If you are inconvenient to use the environment in your machine, you can use the docker to configure the runtime environment.
