### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by Lottie641** [kinredon/umt#2]
I am very interested in your article, but I have a question about the clipart_cycle_voc and voc_cycle_clipart dataset. And where I can download these two datasets?
I will appreciate it if you can provide the drive link.

**Comment by kinredon** [comment]
I have uploaded the data to google drive, contact me via email, I will share the drive link with you.

**Comment by kaiabco1996** [comment]
Hello @kinredon can u pls pass me the link to the datasets as well? my email is karthik.karthika@gmail.com

**Comment by kinredon** [comment]
@kaiabco1996 Hi, I have sent you an email.
