### ISSUE TITLE
大佬，请问可以用百度网盘等提供一下city2foggy的文件嘛（除图片外）

### ISSUE THREAD

**Issue by caiyancheng** [kinredon/umt#3]
/mnt/data0/home/dengjinhong/dataset/city2foggy
请问大佬能提供下这个文件夹内的内容嘛（除图片），万分感谢！

**Comment by caiyancheng** [comment]
这是我的邮箱地址19307140030@fudan.edu.cn

**Comment by kinredon** [comment]
是要那个标注文件吗？我是用这个生成的 https://github.com/yuhuayc/da-faster-rcnn/tree/master/prepare_data （matlab 版本）， 不过也可以参考 https://github.com/yuhuayc/da-faster-rcnn/pull/18 （python 版本）

**Comment by caiyancheng** [comment]
我使用matlab生成的好像都到一个文件夹里去了，但是看您这里的代码好像是不同文件夹的
这是matlab生成的结果：
![image](https://user-images.githubusercontent.com/70524893/134522543-4a0828e7-cfa6-4117-b56e-a6afebab4e75.png)
这是您的代码：
![image](https://user-images.githubusercontent.com/70524893/134522491-0eb71f51-aba5-4a1b-8589-c1e03fc27573.png)

**Comment by kinredon** [comment]
这是因为我有多个数据集，你可以试试单独生成。不着急的话，等我整理好了发给你哈。

**Comment by Fly-dream12** [comment]
你好 请问https://github.com/yuhuayc/da-faster-rcnn/pull/18/files 这个函数里面,好像不涉及中间域呢? 请问若A到B进行cyclegan是生成的标注和A一致的中间域图像吧? 这一部分能举一下xml和jpg的例子吗? 另外想问问lib/datasets/city_unit_foggy.py这类混合数据是否没有用到呢?

**Comment by kinredon** [comment]
A到B进行cyclegan生成的数据标注是和 A 一致的。

**Comment by Fly-dream12** [comment]
直接把a的标注当成中间域的标注吧？ 那city_unit_foggy里面是直接混合的数据吗？好像没看到用过。
能留个邮箱问下具体的问题吗？ 谢谢
