### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by huihui0000** [kinredon/umt#4]
I am very interested in your article, but I have a question about the clipart_cycle_voc and voc_cycle_clipart dataset. 
And where I can download these two datasets?
I will appreciate it if you can provide the drive link.

**Comment by kinredon** [comment]
@huihui0000 Please contact me via email, I will seed you the google drive link.

**Comment by huihui0000** [comment]
My email is luoguiyang@bupt.edu.cn  Please send me the google drive link. Thanks a lot.

**Comment by Irvingkkk** [comment]
Hi, my email is 1046792671@qq.com, could you please send me the google drive link, I want to download the city_cycle_foggy_voc and foggy_cycle_city_voc dataset. Thank you!
