### ISSUE TITLE
ImportError: /home/z/code/kch/umt/lib/model/roi_crop/_ext/roi_crop/_roi_crop.so: undefined symbol: state

### ISSUE THREAD

**Issue by kongyan66** [kinredon/umt#6]
作者你好，我使用CUDA9.0 GCC5.4  进行编译llib/model 下包，编译过程也未报错，为何执行训练时.so包还是无法导入呢？还请指教，谢谢！
![image](https://user-images.githubusercontent.com/68680103/143681410-464c1030-7e36-4329-9b7f-5d1e5f13b80e.png)
![image](https://user-images.githubusercontent.com/68680103/143681419-82598814-6b96-4373-a6f8-08b0ecacaf15.png)

**Comment by kinredon** [comment]
这个问题我好像没有遇到过，但是是环境编译的问题，在 https://github.com/jwyang/faster-rcnn.pytorch 的issue下看一下应该可以找到答案

**Comment by kongyan66** [comment]
好的，谢谢你的答复，我再找找看
