### ISSUE TITLE
关于论文3.4.3的问题

### ISSUE THREAD

**Issue by Irvingkkk** [kinredon/umt#7]
大佬你好！你的工作很出色，就是我对论文里3.4.3 Healing the Teaching Process这一节没怎么看懂，student模型的source这一支为什么要衡量分布内的置信度然后生成soft label呢？teacher模型对source-like图像为什么也要用这个置信度筛选分布内的那部分作为伪标签呢？想问一下这样设计的原因是什么，谢谢！！～～

**Comment by kinredon** [comment]
第一个问题可以参考文章的reference[7]. 第二个问题的原因是学这个置信度的目的就是用他来晒选sourxe like 预测的 instance，然后得到更高质量的pseudo label。

[7] Terrance DeVries and Graham W Taylor. Learning conﬁdence for out-of-distribution detection in neural networks

**Comment by Irvingkkk** [comment]
感谢~
