### ISSUE TITLE
Hello, Thankyou for this repository. Can you please explain the difference between 'city_cycle_foggy_voc' and 'foggy_cycle_city_voc'

### ISSUE THREAD

**Issue by tilahun12** [kinredon/umt#8]

**Comment by kinredon** [comment]
@AstuWeb  `city_cycle_foggy_voc ` refers to the cityscape dataset with foggy style~(i.e. target-like data), and vice versa.

**Comment by tilahun12** [comment]
Thank you for the quick reply. I faced difficulty getting those datasets. I would appreciate it if you can send the datasets or the link where I can find by this Email tilahun003@gmail.com, please.

**Comment by kinredon** [comment]
Because of the dataset Offical policy, I have no right to distribute the Foggy Cityscapes. You may contact them in [here](https://www.cityscapes-dataset.com/foggydownload/).
